# Generated by Django 2.2.12 on 2020-06-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='child_comment_id',
            new_name='parent_comment_id',
        ),
    ]
