# Generated by Django 2.2.12 on 2020-06-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200604_2031'),
        ('blog', '0003_auto_20200604_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_history',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
