"""
    v1.1
    6-5-16-05

    -->tools  models   views  url


Django settings for PYMARA project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9w1f*iwjly!u#a53*7&w7=w4_4lzuexr(s+1!v0(bjqkn6n51&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'blog',
    'user',
    'index',
    'logreg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PYMARA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PYMARA.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'PYMARA',
        'USER': 'root',
        'PASSWORD': 'sakura',
        'HOST': '127.0.0.1',
        'PORT': '3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# cors 跨域
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)
CORS_ALLOW_HEADERS = (
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'pymaratoken',
)

JWT_TOKEN_KEY = "0TLNWooggVcDzSkK"

# chenPyMara
MY_WB_APP_KEY = "94814943"
MY_WB_APP_SECRET = "6da055316c29759cbeb7e05b3adef1c2"
MY_WB_REDIRECT_URI = "http://127.0.0.1:7004/pymara/templates/user/callback.html"

# PyMara 正式上线
# MY_WB_APP_KEY = "2734830647"
# MY_WB_APP_SECRET = "b52607cd1d66b1bb291b96888770820c"
# MY_WB_REDIRECT_URI = "http://121.196.122.72:7000/pymara/templates/user/callback.html"
# "http://121.196.122.72:7000/pymara/templates/index.html"


# 方案一
# from django.core.cache import caches
# cache = caches["default"]

# 　方案二
# from django_redis import get_redis_connection
# r = get_redis_connection(alias="default")


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": "xxxxx",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",  # 压缩
        }
    },
    "cache_15": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/15",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": "xxxxx",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        }
    },
}

MY_MEDIA_URL = "/Media/"
MY_MEDIA_ROOT = os.path.join(BASE_DIR, "Media")
# 图片访问地址前缀
MY_PIC_URL = "http://127.0.0.1:8000" + MY_MEDIA_URL

# 图片
MEDIA_ROOT = "/var/www/html/pymara/media/"
MEDIA_URL = '/pymara/media/'

# redis 9库
# blog_info_<blog_id>
BLOG_INFO_KEY = 'blog_info_'
BLOG_CACHE_IDS_KEY = 'blog_cache_ids'
RANK_HOT_KEY = 'blog_rank_hot_ids'
SCORE_ALGORITHM = {
    'browse': 1,
    'praise': 10,
    'comment': 50,
    'favorite': 50,
}
# redis更新条件 >=
REDIS_BLOG_INFO_UPDATE = 1000
